using System;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.SignalR;

namespace SacramentMeetingPlanner.Models
{
    public class Member
    {
        public int ID { get; set; }

        [Display (Name = "First Name")]
        [StringLength(20, MinimumLength = 3)]
        [RegularExpression(@"^[A-Z]+[a-zA-Z""'\s-]*$")]
        [Required]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        [StringLength(20, MinimumLength = 3)]
        [RegularExpression(@"^[A-Z]+[a-zA-Z""'\s-]*$")]
        [Required]
        public string LastName { get; set; }

        [Display (Name = "Title")]
        [Required]
        public Title MemberTitle { get; set; }
    }

    public enum Title
    {
        President,
        Bishop,
        Elder,
        Sister,
        Brother,
        Patriarch
    }

    public enum Topic
    {
        "Aaronic Priesthood",
        "Abortion",
        "Abraham, Book of",
        "Abrahamic Covenant",
        "Abuse"
        /*Addiction,
        Adoption,
        Adversity,
        Agency and Accountability,
        Answering Gospel Questions,
        Apostasy,
        Apostle,
        Are Mormons Christian?,
        Articles of Faith,
        Atonement of Jesus Christ,
        Baptism,
        Baptisms for the Dead,
        Becoming Like God,
        Bible,
        Bible\, Inerrancy of,
        Birth Control,
        Bishop,
        Book of Mormon,
        Book of Mormon and DNA Studies,
        Book of Mormon Geography,
        Book of Mormon Translation,
        Celestial Kingdom,
        Charity,
        Chastity,
        Christmas,
        Church Councils,
        Church Finances—Commercial Businesses,
        Citizenship,
        Communication,
        Conscience,
        Consecration,
        Conversion,
        Council in Heaven,
        Covenant,
        Creation,
        Cross,
        Dating and Courtship,
        Daughters in My Kingdom,
        Deacon,
        Death\, Physical,
        Death\, Spiritual,
        Debt,
        Disabilities,
        Dispensations,
        Diversity and Unity in The Church of Jesus Christ of Latter-day Saints,
        Divorce,
        Doctrine and Covenants,
        Easter,
        Education,
        Elder,
        Emergency Preparedness,
        Emergency Response,
        Employment,
        Endowment,
        Environmental Stewardship and Conservation,
        Eternal Life,
        Faith in Jesus Christ,
        Fall of Adam and Eve,
        Family,
        Family Councils,
        Family Finances,
        Family History,
        Fasting and Fast Offerings,
        First Presidency,
        First Vision,
        First Vision Accounts,
        Food Storage,
        Foreordination,
        Forgiveness,
        Gambling,
        Gardening,
        Garments,
        Godhead,
        God the Father,
        Gold Plates,
        Gospel,
        Grace,
        Gratitude,
        Grief,
        Happiness,
        Health,
        Heaven,
        Heavenly Parents,
        Hell,
        High Council,
        High Priest,
        Holy Ghost,
        Home Evening,
        Honesty,
        Hope,
        Humility,
        Immortality,
        Jesus Christ,
        Doctrinal Study,
        Jesus Christ Chosen as Savior,
        Joseph Smith,
        Joseph Smith’s Teachings about Priesthood\, Temple\, and Women,
        Journal of Discourses,
        Judging Others,
        Justice,
        Kingdoms of Glory,
        Laying On of Hands,
        Light of Christ,
        Love,
        Marriage,
        Media,
        Melchizedek Priesthood,
        Membership Councils,
        Mercy,
        Millennium,
        Ministering,
        Miracles,
        Missionary Work,
        Modesty,
        Mormon Church,
        Mormonism,
        Mormons,
        Mortality,
        Mother in Heaven,
        Mountain Meadows Massacre,
        Music,
        New Testament,
        Noah,
        Obedience,
        Old Testament,
        Ordinances,
        Original Sin,
        Paradise,
        Parenting,
        Patriarch,
        Patriarchal Blessings,
        Peace,
        Peace and Violence among 19th-Century Latter-day Saints,
        Pearl of Great Price,
        Peer Pressure,
        Plan of Salvation,
        Plural Marriage,
        Pornography,
        Postmortality,
        Prayer,
        Premortality,
        Priest,
        Priesthood,
        Priesthood and Race,
        Priesthood Blessing,
        Primary,
        Prison Ministry,
        Profanity,
        Prophecy,
        Prophets,
        Proxy Baptism,
        Quorum,
        Quorum of the Twelve Apostles,
        Race and the Priesthood,
        Racial and Cultural Prejudice,
        Relief Society,
        Religious Freedom,
        Repentance,
        Restoration of the Church,
        Restoration of the Priesthood,
        Resurrection,
        Revelation,
        Reverence,
        Sabbath Day,
        Sacrament,
        Sacrament Meeting,
        Sacrifice,
        Salvation,
        Same-Sex Attraction,
        Same-Sex Marriage,
        Satan,
        Scriptures,
        Sealing,
        Second Coming of Jesus Christ,
        Self-Reliance,
        Service,
        Sex Education and Behavior,
        Signs,
        Sin,
        Single Adult Members of the Church,
        Single-Parent Families,
        Soul,
        Spaulding Manuscript,
        Spirit,
        Spirit Children of Heavenly Parents,
        Spiritual Experiences,
        Spiritual Gifts,
        Spirit World,
        Stake,
        Standard Works,
        Stewardship,
        Suicide,
        Tattooing and Body Piercing,
        Teacher (Aaronic Priesthood),
        Teaching the Gospel,
        Telestial Kingdom,
        Temples,
        Temptation,
        Ten Commandments,
        Terrestrial Kingdom,
        Testimony,
        The Manifesto and the End of Plural Marriage,
        Tithing,
        Transgender,
        Transgression,
        Translation and Historicity of the Book of Abraham,
        Unity,
        Unwed Pregnancy,
        Urim and Thummim,
        Vicarious Work,
        Virtue,
        War,
        War in Heaven,
        Witness,
        Women in the Church,
        Word of Wisdom,
        Worship,
        Zion*/
    }
}
